In [29]:
def C_to_F_temp(C): #define used for function (an initializer)
                    #the (C) creates a variable for the function that the user places in the paranthesis
    #F = (C*(9/5)+32)
    fahrenheit = (C*(9/5)+32)
    print(fahrenheit) #gives us the answer after the function runs but may not allow us to reuse
    return fahrenheit #recalls the final fahrenheit, allows you to manipulate/use

In [30]:
C_to_F_temp(100)

212.0

212.0

In [77]:
#make a fnxn that converts fahrenheit to celsius
#C = (F-32)*(5/9)
#allow user to specify the input
#define a default
def FtoC_Temp (F): #variable F for user to put in user input
    if F == (""):
        return('Water"s boiling point in C is 100 C.')
    else :
        C = (F-32)*(5/9);
        return(C)

In [78]:
FtoC_Temp()

TypeError: FtoC_Temp() missing 1 required positional argument: 'F'

In [55]:
import pandas as pd

In [74]:
dem_health_data = pd.read_csv("Dem_Health_Full.txt", sep='\t')

In [76]:
dem_health_data.head(20)

,County,State,Population_Density,Poverty,Infant_Mortality,Suicide,Total_Births,Total_Deaths
0,Autauga,AL,82,10.4,5.9,16.6,3048.0,1867.0
1,Baldwin,AL,102,10.2,7.1,14.3,5471.0,4388.0
2,Barbour,AL,32,22.1,7.1,10.3,1835.0,1538.0
3,Bibb,AL,35,16.8,9.8,14.8,2801.0,2012.0
4,Blount,AL,86,11.9,9.0,14.4,3318.0,2453.0
5,Bullock,AL,18,26.2,13.3,-1111.1,1604.0,1381.0
6,Butler,AL,27,20.0,5.8,11.9,2874.0,2857.0
7,Calhoun,AL,184,16.4,9.5,13.6,4429.0,3915.0
8,Chambers,AL,59,16.2,7.5,12.8,2271.0,2424.0
9,Cherokee,AL,44,15.2,7.4,17.7,2659.0,2609.0
10,Chilton,AL,60,14.9,10.5,13.3,2671.0,2065.0
11,Choctaw,AL,16,18.7,10.8,9.4,2152.0,1742.0
12,Clarke,AL,22,19.2,7.1,8.9,1984.0,1444.0
13,Clay,AL,23,14.0,10.2,11.2,1748.0,1706.0
14,Cleburne,AL,26,14.0,7.0,30.1,1706.0,1540.0
15,Coffee,AL,67,13.7,2.9,13.1,2762.0,2210.0
16,Colbert,AL,92,14.0,8.2,15.1,3166.0,3087.0
17,Conecuh,AL,16,22.0,14.4,13.2,1872.0,1832.0
18,Coosa,AL,17,13.4,13.9,-1111.1,1273.0,1174.0
19,Covington,AL,36,17.5,6.2,10.7,2247.0,2499.0

In [94]:
def get_urban(dF,threshold):
    urban= dF.loc[dF['Population_Density'] >= threshold, :]
    return (urban)

In [95]:
urban_counties=get_urban(dem_health_data, 2500)

In [97]:
urban_counties

,County,State,Population_Density,Poverty,Infant_Mortality,Suicide,Total_Births,Total_Deaths
213,Orange,CA,3785,10.6,4.7,7.6,135702.0,51060.0
221,San Francisco,CA,15837,12.0,3.9,11.0,25255.0,18969.0
258,Denver,CO,3638,15.1,6.7,14.2,34354.0,13530.0
317,Washington,DC,8966,17.5,10.9,6.0,22742.0,17375.0
369,Pinellas,FL,3315,12.1,7.6,16.3,27592.0,37641.0
428,DeKalb,GA,2528,13.2,9.2,9.7,32375.0,11887.0
608,Cook,IL,5608,14.5,8.5,7.5,247949.0,134307.0
614,DuPage,IL,2785,5.9,6.6,7.3,39133.0,17092.0
1146,Orleans,LA,2519,25.5,11.7,9.4,21237.0,15084.0
1214,Baltimore City,MD,7869,19.6,11.1,8.2,28958.0,24321.0
1227,Suffolk,MA,11183,15.9,6.1,5.7,28649.0,16317.0
1310,Wayne,MI,3254,16.5,11.2,10.3,88716.0,59647.0
1373,Ramsey,MN,3177,10.7,5.6,9.1,22222.0,11712.0
1595,St. Louis City,MO,5561,21.3,12.8,13.1,15755.0,12366.0
1773,Bergen,NJ,3854,6.1,4.4,6.2,31845.0,22741.0
1778,Essex,NJ,6265,14.4,8.6,5.5,36577.0,21091.0
1780,Hudson,NJ,12926,15.0,7.4,4.8,26507.0,13726.0
1783,Middlesex,NJ,2549,7.4,4.8,6.1,31989.0,16653.0
1787,Passaic,NJ,2693,12.6,6.0,6.6,23317.0,12091.0
1791,Union,NJ,5145,9.9,6.1,5.4,22768.0,13636.0
1828,Bronx,NY,32300,26.8,6.8,5.8,68201.0,30886.0
1849,Kings,NY,35211,23.3,6.5,4.6,119171.0,54937.0
1855,Nassau,NY,4650,5.9,4.7,4.8,48734.0,33965.0
1856,New York,NY,69390,18.6,4.9,8.2,60627.0,34423.0
1866,Queens,NY,20520,15.4,5.2,4.7,92216.0,47876.0
1868,Richmond,NY,7944,10.1,5.0,6.0,17514.0,11023.0
2058,Cuyahoga,OH,2912,13.5,9.1,10.4,52896.0,45286.0
2264,Delaware,PA,3016,8.9,6.9,8.9,20217.0,17172.0
2292,Philadelphia,PA,10832,20.1,10.4,10.7,64853.0,50895.0
2577,Dallas,TX,2621,16.9,6.8,10.6,128098.0,42119.0
2824,Arlington,VA,7575,7.4,4.2,7.6,8541.0,3244.0
2846,Fairfax,VA,2548,5.8,4.7,7.3,43498.0,12822.0
2913,Alexandria City,VA,8915,8.8,5.9,8.5,7852.0,2432.0
2917,Charlottesville City,VA,3941,17.8,7.4,11.6,2553.0,1737.0
2923,Fairfax City,VA,3481,5.5,6.7,13.2,3271.0,2080.0
2924,Falls Church City,VA,5418,3.0,5.4,9.4,1866.0,790.0
2928,Hampton City,VA,2811,13.1,11.6,8.5,5611.0,3410.0
2931,Lexington City,VA,2721,16.1,NaN,-1111.1,558.0,767.0
2933,Manassas City,VA,3783,7.5,4.5,-1111.1,3593.0,959.0
2934,Manassas Park City,VA,4667,6.5,6.3,-1111.1,1915.0,347.0
2936,Newport News City,VA,2634,14.0,11.7,10.1,9587.0,4220.0
2937,Norfolk City,VA,4317,19.8,11.0,12.6,12143.0,6226.0
2941,Portsmouth City,VA,3021,16.5,14.2,13.4,4726.0,3254.0
2943,Richmond City,VA,3226,20.2,14.8,11.5,9287.0,6989.0
2951,Winchester City,VA,2692,12.0,8.0,15.8,3336.0,2628.0
3086,Milwaukee,WI,3815,16.2,10.4,11.4,43885.0,26557.0

In [124]:
def split_county_by_pop(dF, threshold):
        urban= dF.loc[dF['Population_Density'] >= threshold, :]
        rural= dF.loc[dF['Population_Density'] < threshold, :]
        return[urban,rural]

In [117]:
rural_counties = \
split_county_by_pop(dem_health_data,500)# "\" allows you to continue typing your function in the next line

In [130]:
rural_counties[1].min()

County                Abbeville
State                        AK
Population_Density        -2222
Poverty                     2.2
Infant_Mortality              0
Suicide                 -2222.2
Total_Births            -2222.2
Total_Deaths            -2222.2
dtype: object

In [132]:
len(rural_counties[0])

235